In [2]:
import sys
sys.path.append('../..')
import multicomp as mm
import numpy as np

# Obtain coexisting phases for an arbitrary interaction matrix and average compositions
Note: package assumes the existence of an inert solvent, determined by the incompressibility condition.

## system settings

In [3]:
# an arbitrary symmetric matrix of 4 components + 1 inert solvent.
# The interaction between components and the solvent is assume to be zero.
# Note that the diagonal elements are not necessary to be zero.
# With non-zero diagonal elements, the system will be effective interactions between solvent and other components.
chi_matrix = [
    [0.0, 4.0, 5.0, 6.0],
    [4.0, 0.0, 7.0, 6.0],
    [5.0, 7.0, 0.0, 3.0],
    [6.0, 6.0, 3.0, 0.0],
]

chi_matrix = [
    [0.0, 4.0, 5.0, 2.0],
    [4.0, 0.0, 3.0, 2.0],
    [5.0, 3.0, 0.0, 3.0],
    [2.0, 2.0, 3.0, 0.0],
]

# average compositions of the entire system
# the volume fraction of the solvent is determined by incompressibility
phi_vector = [0.2, 0.1, 0.3, 0.2]

In [10]:
num_compartments = 64
phis = [phi_vector] * num_compartments

arr_phi = np.array(phis)
arr_vol = np.ones(num_compartments) / num_compartments

print(arr_phi)
print(arr_vol.shape)

[[0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.3 0.2]
 [0.2 0.1 0.

## Create some compartments

In [11]:
# number of phases that the system will generate
num_compartments = 64 # a overkill but safe choice for 4+1 components
# create the Flory-Huggins free energy
fh_energy = mm.FloryHuggins(np.array(chi_matrix))
# generate a collection of compartments
# we generate compartments that all of them share the same composition, namely the average composition, here.
# the FieldLikeRelaxationDynamics afterwards will add fluctuations to the compositions itself.
phis = [phi_vector] * num_compartments


mixture = mm.MultiphaseVolumeSystem(
    fh_energy, 
    np.array(phis), # compositions of each compartment
    np.ones(num_compartments) / num_compartments # relative volume of each compartment
)

[[0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1, 0.3, 0.2], [0.2, 0.1

In [7]:
type(mixture)

multicomp.mixture.MultiphaseVolumeSystem

## Hyperparameters 

In [4]:
dynamics_params = {
    "initialization_random_std": 5,  # how random the initial guess is
    "acceptance_Js": 0.0002, # how fast the relative volumes are evolved
    "acceptance_omega": 0.002, # how fast the compositions are evolved
}

evolve_params = {
    "t_range": 1000000,  # maximum iteration steps
    "dt": 1,  # always unity for FieldLikeRelaxationDynamics
    "interval": 10000,  # the frequency for checking convergence
    "tolerance": 1e-5,  # criteria for determining convergence
    "progress": True,
    "save_intermediate_data": False,
}

## Create the dynamics and find the coexisting states

In [5]:
dynamics = mm.FieldLikeRelaxationDynamics(mixture, parameters=dynamics_params)
ts, result = dynamics.evolve(**evolve_params)

## Print and Check

In [26]:
unique_phases = result.get_clusters()
print(len(unique_phases), "phases are found")
print("Compositions are ")
print(unique_phases)
print("Convergence is (lower the better) ")
print(result.entropy_production)


2 phases are found
Compositions are 
[[0.02828841 0.07972509 0.63568611 0.08158511]
 [0.3004376  0.1118592  0.10365038 0.26926327]]
Convergence is (lower the better) 
4.1540370006867606e-07
