In [33]:
import numpy as np
import flory
import sys

sys.path.append('/Users/calvinsmith/dufresne_lab/phase_space_search/')
import flory_classifier_v2
import flory_phase_space
from flory_classifier_v2 import FloryClassifier 
from flory_phase_space import PhaseSpace

## Generate Matrices

In [38]:
num_points = 10
num_comps = 3

In [42]:
points = np.random.rand(num_points,num_comps)
points = points/ points.sum(axis = 1, keepdims = True)


In [41]:
print(points)

[[0.35267489 0.25774633 0.38957878]
 [0.22013607 0.47150882 0.30835511]
 [0.5523392  0.16847986 0.27918094]
 [0.08223081 0.27642279 0.6413464 ]
 [0.20588573 0.65369026 0.14042401]
 [0.60027931 0.1545893  0.2451314 ]
 [0.44808216 0.40302061 0.14889723]
 [0.15229449 0.38029277 0.46741274]
 [0.44722723 0.2361643  0.31660847]
 [0.18155384 0.57683655 0.24160961]]
